server:
  port: 9080
  contextPath: /uaa
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat

security:
  basic:
    enabled: false

spring:
  thymeleaf:
    cache: false

  datasource:
    driverClassName: com.mysql.jdbc.Driver		
    url: jdbc:mysql://192.168.99.100:3306/doasoft?autoReconnect=true&useSSL=false
    username: root
    password: root
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    
  jpa:
    generate-ddl: true # Initialize the schema on startup.
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: none
    show-sql: true
    format_sql: true    

logging:
  level:
    org.springframework.security: DEBUG