server:
 port: 8080
 contextPath: /resource-service
oauth2:
 resource:
 userInfoUri: http://localhost:9080/uaa/user
logging:
 level:
  org.springframework.security: DEBUG
auth:
 server:
  url: http://localhost:9080/uaa/oauth/check_token/
  clientId: soncrserv
  clientsecret: soncrserv
  