# profile: producao

server:
  port: 8181
  contextPath: /agendamento

security:
  user:
    password: none

zuul:
  routes:
    resource:
      path: /resource/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      url: http://174.142.227.104:8080/resource-service/
    user:
      path: /user/**
      url: http://174.142.227.104:8080/resource-service/user
  debug:
    request: true
  add-proxy-headers: true

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html,/app/**,/assets/**
    client:
      accessTokenUri: http://174.142.227.104:9080/uaa/oauth/token
      userAuthorizationUri: http://174.142.227.104:9080/uaa/oauth/authorize
      clientId: soncui
      clientSecret: soncui
      scope: read, write
    resource:
      userInfoUri: http://174.142.227.104:8080/resource-service/user
    thymeleaf:
      cache: false

logging:
  level.org.springframework.security: DEBUG